apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: process_settings
  title: Process Settings gem
  tags:
  - ruby
  annotations:
    github.com/project-slug: invoca/process_settings
    endoflife.date/products: ruby@3.3
spec:
  type: library
  lifecycle: production
  owner: octothorpe
