---
apiVersion: v1
kind: Pod
metadata:
  labels:
    jenkins/process_settings: 'true'
  namespace: jenkins
  name: process_settings
spec:
  tolerations:
  - key: dedicated
    operator: Equal
    value: jenkins
    effect: NoSchedule
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kops.k8s.io/instancegroup
            operator: In
            values:
            - jenkins
  containers:
  - name: ruby
    image: ruby:2.6.5
    tty: true
    resources:
      requests:
        memory: "200Mi"
      limits:
        memory: "500Mi"
    command:
      - cat
