---
apiVersion: v1
kind: Pod
metadata:
  labels:
    jenkins/process_settings: 'true'
  namespace: jenkins
  name: process_settings
spec:
  containers:
  - name: ruby
    image: ruby:2.6.5
    tty: true
    resources:
      requests:
        memory: "400Mi"
      limits:
        memory: "400Mi"
    command:
      - cat
