name: Test Coverage
on: [push]
jobs:
  coverage:
    name: Test Coverage
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v4
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.4
        bundler: 2.3.10
        bundler-cache: true
    - name: Unit Tests
      run: |
        mkdir -p tmp
        bundle exec rspec
    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.github_token }}
