name: Pipeline
on: [push]
jobs:
  tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: [2.6]
        gemfile:
        - Gemfile
        - gemfiles/rails_4.gemfile
        - gemfiles/rails_5.gemfile
        - gemfiles/rails_6.gemfile
    env:
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler: 1.17.3
        bundler-cache: true
    - name: Unit Tests
      run: |
        mkdir -p tmp
        bundle exec rspec
    - name: Coveralls
      if: ${{ matrix.gemfile == 'Gemfile' }}
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.github_token }}
